#!/bin/bash

host="localhost"
port="3001"
user=""
pass=""
lines=""
cmd=""
config="/home/bspaans/.vimchart"

if [ -f "$config" ] ; then
    i=0
    for x in $(awk -F: '{ print $1; print $2 }' "$config") ; do
        if [ $i == 0 ] ; then 
            user="$x"
        else
            pass="$x"
        fi
        i=$(($i + 1))
    done
else
    echo "Missing $config"
    exit 1
fi

if [ "$user" == "" ] || [ "$pass" == "" ] ; then 
    echo "Error: missing username or password."
    echo "Add line formatted as user:pass to $config"
    exit 1
fi




while getopts "en:sw:" flag
do
    case "$flag" in
        e|ended)
        cmd="vimEnded"
        ;;
        h|host)
        host=$OPTARG
        ;;
        n|new)
        cmd="newFile $OPTARG"
        ;;
        p|port)
        port=$OPTARG
        ;;
        s|started)
        cmd="vimStarted"
        ;;
        w|write)
        cmd="writeFile $OPTARG"
        ;;
    esac
done

if [ "$cmd" == "" ] ; then 
    echo "Error: Missing options "
    echo
    echo "Usage: $0 [OPTIONS]"
    echo "Options:"
    echo "    -e --ended          Vim session ended"
    echo "    -h HOST             (default localhost)"
    echo "    -n --new            Editing new file"
    echo "    -p PORT             (default 3000)"
    echo "    -s --started         Vim session started"
    echo "    -w --write FILE      Written file"
    exit 1
fi

cat > tmp.session << EOF
login $user $pass
$cmd
quit
EOF

cat tmp.session | telnet $host $port >& /dev/null

rm tmp.session
