#!/bin/bash

host="localhost"
port="3141"
lines=""
cmd=""

while getopts "eh:n:p:sw:" flag
do
    case "$flag" in
        e|ended)
        cmd="END"
        ;;
        h|host)
        host=$OPTARG
        ;;
	help)
	cmd=""
	;;
        n|new)
        cmd="NEW $OPTARG"
        ;;
        p|port)
        port=$OPTARG
        ;;
        s|started)
        cmd="START"
        ;;
        w|write)
        cmd="EDIT $OPTARG"
        ;;
    esac
done

if [ "$cmd" == "" ] ; then 
    echo "Error: Missing options "
    echo
    echo "Usage: $0 [OPTIONS]"
    echo "Options:"
    echo "    -e                  Session ended"
    echo "    -h HOST             (default localhost)"
    echo "    -n                  Editing new file"
    echo "    -p PORT             (default 3141)"
    echo "    -s                  Session started"
    echo "    -w FILE             Written file"
    exit 1
fi

t="$(tempfile)"
cat > "$t" << EOF
$cmd
quit
EOF

cat "$t" | telnet $host $port >& /dev/null

rm "$t"
